export const createFinanceDefaults = () => ({
  monthly_fee: '',
  monthly_fee_by_grade: {},
  fee_rules: [],
  comment: '',
  included_in_tuition: '',
  extra_fees: '',
  registration_fee: '',
  registration_fee_currency: 'KZT',
  payment_system: '',
  payment_options: [],
  discounts_info: '',
  grants_info: '',
  grants_discounts: '',
  free_places: false,
  funding_state: false,
  funding_self: false,
});

export const createEmptySchoolProfile = (overrides: any = {}) => {
  const base = {
    school_id: '',
    basic_info: {
      name: { ru: '', en: '', kk: '' },
      display_name: { ru: '', en: '', kk: '' },
      type: '',
      school_subtype: '',
      city: '',
      district: '',
      address: { ru: '', en: '', kk: '' },
      additional_locations: [],
      description: { ru: '', en: '', kk: '' },
      coordinates: {
        latitude: '',
        longitude: '',
      },
      phone: '',
      whatsapp_phone: '',
      email: '',
      website: '',
      founded_year: '',
      team: {
        principal: '',
        deputy_principal: '',
        leadership: {
          principal: {
            full_name: '',
            position: 'Директор',
            photo_url: '',
            bio: { ru: '', en: '', kk: '' },
          },
          deputy_principal: {
            full_name: '',
            position: 'Зам. директора',
            photo_url: '',
            bio: { ru: '', en: '', kk: '' },
          },
        },
        class_curators: '',
        class_curators_enabled: false,
        class_curators_format: '',
        class_curators_comment: { ru: '', en: '', kk: '' },
      },
      license_details: {
        number: '',
        issued_at: '',
        valid_until: '',
      },
      license_accreditation: '',
    },
    education: {
      languages: '',
      languages_other: { ru: '', en: '', kk: '' },
      grades: '',
      programs: { ru: '', en: '', kk: '' },
      curricula: {
        national: [],
        international: [],
        additional: [],
        other: { ru: '', en: '', kk: '' },
      },
      advanced_subjects: '',
      advanced_subjects_other: { ru: '', en: '', kk: '' },
      average_class_size: '',
      entrance_exam: {
        required: false,
        format: '',
        format_other: { ru: '', en: '', kk: '' },
        subjects: '',
        subjects_other: { ru: '', en: '', kk: '' },
        stages: { ru: '', en: '', kk: '' },
      },
      admission_details: {
        has_available_seats: false,
        seats_by_grade: '',
        enrollment_period: '',
        document_deadlines: '',
        admission_stages_detail: { ru: '', en: '', kk: '' },
        competition_per_seat: '',
        application_channel: [],
        application_link: '',
        residential_assignment: false,
        admission_first_grade: false,
        admission_transfer: false,
        residence_required: false,
        competitive_selection: false,
        specialized_classes: false,
        documents_detail: { ru: '', en: '', kk: '' },
        parent_comment: { ru: '', en: '', kk: '' },
      },
      admission_rules: [],
      results: {
        average_exam_score: '',
        university_admission_rate: '',
        top_universities: { ru: '', en: '', kk: '' },
        olympiad_achievements: { ru: '', en: '', kk: '' },
        student_success_stories: [],
      },
      learning_conditions: {
        class_size_primary: '',
        class_size_middle: '',
        class_size_high: '',
        shift_mode: '',
        homework_format: { ru: '', en: '', kk: '' },
        assessment_format: { ru: '', en: '', kk: '' },
        digital_platforms: '',
      },
    },
    services: {
      after_school: false,
      after_school_until: '',
      meals: '',
      meals_status: '',
      meals_times_per_day: '',
      meals_free_until_grade: '',
      meals_price: '',
      meals_currency: 'KZT',
      meals_notes: { ru: '', en: '', kk: '' },
      foreign_teachers: false,
      foreign_teachers_notes: { ru: '', en: '', kk: '' },
      teaching_staff: {
        photo: '',
        description: { ru: '', en: '', kk: '' },
        members: [],
      },
      transport: false,
      transport_details: {
        routes: { ru: '', en: '', kk: '' },
        cost_by_district: { ru: '', en: '', kk: '' },
        pickup_schedule: { ru: '', en: '', kk: '' },
        dropoff_schedule: { ru: '', en: '', kk: '' },
      },
      inclusive_education: false,
      specialists: '',
      specialists_other: { ru: '', en: '', kk: '' },
      clubs: '',
      clubs_unified: [],
      clubs_catalog: [],
      clubs_other: {
        ru: {
          sports: '',
          arts: '',
          stem: '',
          language: '',
          leadership: '',
          other: '',
        },
        en: {
          sports: '',
          arts: '',
          stem: '',
          language: '',
          leadership: '',
          other: '',
        },
        kk: {
          sports: '',
          arts: '',
          stem: '',
          language: '',
          leadership: '',
          other: '',
        },
      },
      safety: {
        security: false,
        cameras: false,
        access_control: false,
        security_protocols: { ru: '', en: '', kk: '' },
        access_policy: { ru: '', en: '', kk: '' },
      },
      medical_office: false,
      psychologists: false,
      speech_therapists: false,
      social_workers: false,
      tutors: false,
      special_educators: false,
      nurses: false,
      defectologists: false,
      health_support: {
        medical_staff: { ru: '', en: '', kk: '' },
        medical_hours: { ru: '', en: '', kk: '' },
        psychologist_support: '',
        logopedist_support: '',
        defectologist_support: '',
        allergy_support: { ru: '', en: '', kk: '' },
      },
      parent_engagement: {
        feedback_format: { ru: '', en: '', kk: '' },
        meeting_frequency: { ru: '', en: '', kk: '' },
        parent_committee: '',
        response_sla_hours: '',
      },
    },
    finance: createFinanceDefaults(),
    media: {
      photos: '',
      videos: '',
      logo: '',
      logo_local_uri: '',
      certificates: '',
      social_links: {
        instagram: '',
        tiktok: '',
        youtube: '',
        facebook: '',
        vk: '',
        telegram: '',
        linkedin: '',
      },
    },
    location: {
      transport_stop_type: '',
      nearest_metro_stop: { ru: '', en: '', kk: '' },
      nearest_bus_stop: { ru: '', en: '', kk: '' },
      distance_to_metro_km: '',
      distance_to_bus_stop_km: '',
      service_area: { ru: '', en: '', kk: '' },
    },
    system: {
      reviews_count: 0,
      rating: 0,
      updated_at: '',
      created_at: '',
      is_active: true,
      hidden_from_users: false,
      audit_log: [],
      notifications: [],
    },
    monetization: {
      is_promoted: false,
      subscription_status: 'inactive',
      plan_name: '',
      priority_weight: 0,
      starts_at: '',
      ends_at: '',
      last_tariff_id: '',
      payments: [],
    },
  };

  return mergeDeep(base, overrides);
};

const mergeDeep = (target: any, source: any) => {
  const output = { ...target };
  if (!source || typeof source !== 'object') return output;
  Object.keys(source).forEach((key) => {
    if (
      source[key] &&
      typeof source[key] === 'object' &&
      !Array.isArray(source[key])
    ) {
      output[key] = mergeDeep(target[key] || {}, source[key]);
    } else {
      output[key] = source[key];
    }
  });
  return output;
};
