const CURRICULA_INFO = {
  'State program (Kazakhstan)': {
    aliases: ['State program', 'State program (Kazakhstan)', 'Госпрограмма (Казахстан)', 'Мемлекеттік бағдарлама (Қазақстан)'],
    ru: {
      title: 'Госпрограмма (Казахстан)',
      short: 'Обучение по государственным стандартам РК и типовым учебным планам.',
      includes: 'Обязательные предметы по классам, стандартная аттестация, подготовка к национальным требованиям.',
      forWho: 'Подходит семьям, которым важна предсказуемая траектория в системе РК.',
      workload: 'Средняя',
      outcome: 'Переход между школами РК, подготовка к национальным экзаменам.',
      risks: 'Меньше гибкости и международных модулей, чем в международных треках.',
    },
    en: {
      title: 'State program (Kazakhstan)',
      short: 'Education aligned with Kazakhstan state standards and typical plans.',
      includes: 'Mandatory grade-level subjects, standard assessment, preparation for national requirements.',
      forWho: 'Best for families who need a predictable local path.',
      workload: 'Medium',
      outcome: 'Smooth transfer inside KZ schools and national exam readiness.',
      risks: 'Less flexibility and fewer international modules than global tracks.',
    },
    kk: {
      title: 'Мемлекеттік бағдарлама (Қазақстан)',
      short: 'ҚР мемлекеттік стандарттары мен типтік жоспарларына сай оқу.',
      includes: 'Сынып бойынша міндетті пәндер, стандартты бағалау, ұлттық талаптарға дайындық.',
      forWho: 'Қазақстан жүйесінде тұрақты оқу траекториясын қалайтын отбасыларға.',
      workload: 'Орташа',
      outcome: 'ҚР мектептері арасында ауысу және ұлттық емтихандарға дайындық.',
      risks: 'Халықаралық бағдарламаларға қарағанда икемділігі төмен.',
    },
  },
  'Updated content': {
    aliases: ['Updated content', 'Обновленное содержание', 'Жаңартылған мазмұн'],
    ru: {
      title: 'Обновленное содержание',
      short: 'Компетентностный подход: знания + применение на практике.',
      includes: 'Критериальное оценивание, проектные задания, функциональная грамотность.',
      forWho: 'Тем, кто хочет современный учебный подход и развитие навыков.',
      workload: 'Средняя',
      outcome: 'Сильная база самостоятельности, анализа и практического мышления.',
      risks: 'Требует большей вовлеченности и самодисциплины ученика.',
    },
    en: {
      title: 'Updated content',
      short: 'Competency-based learning focused on practical application.',
      includes: 'Criteria-based assessment, projects, functional literacy tasks.',
      forWho: 'Families looking for a more modern learning model.',
      workload: 'Medium',
      outcome: 'Stronger independence, analysis, and applied thinking.',
      risks: 'Demands higher student engagement and self-management.',
    },
    kk: {
      title: 'Жаңартылған мазмұн',
      short: 'Құзыреттілікке негізделген оқыту: білімді тәжірибеде қолдану.',
      includes: 'Критериалды бағалау, жобалық тапсырмалар, функционалдық сауаттылық.',
      forWho: 'Заманауи оқыту форматын қалайтын отбасыларға.',
      workload: 'Орташа',
      outcome: 'Өзіндік жұмыс, талдау және практикалық ойлау дағдылары дамиды.',
      risks: 'Оқушыдан жоғары жауапкершілік пен белсенділік талап етеді.',
    },
  },
  'NIS Integrated Program': {
    aliases: ['NIS Integrated Program', 'Интегрированная программа НИШ', 'НЗМ интеграцияланған бағдарламасы'],
    ru: {
      title: 'Интегрированная программа НИШ',
      short: 'Интеграция нацстандарта и международных академических практик.',
      includes: 'Усиленные предметы, исследовательские и проектные форматы, высокий темп.',
      forWho: 'Для мотивированных учеников с готовностью к интенсивной нагрузке.',
      workload: 'Высокая',
      outcome: 'Сильная академическая подготовка и конкурентный профиль.',
      risks: 'Сложнее адаптация при слабой базе или низкой самоорганизации.',
    },
    en: {
      title: 'NIS Integrated Program',
      short: 'Integration of national standards with international practices.',
      includes: 'Advanced subjects, research and project-based learning, higher pace.',
      forWho: 'Motivated students ready for intensive learning.',
      workload: 'High',
      outcome: 'Strong academic profile and competitive outcomes.',
      risks: 'Harder adaptation for students with weak baseline skills.',
    },
    kk: {
      title: 'НЗМ интеграцияланған бағдарламасы',
      short: 'Ұлттық стандарт пен халықаралық тәжірибенің интеграциясы.',
      includes: 'Күшейтілген пәндер, зерттеу және жобалық оқу, жоғары қарқын.',
      forWho: 'Қарқынды оқуға дайын, мотивациясы жоғары оқушыларға.',
      workload: 'Жоғары',
      outcome: 'Күшті академиялық база және бәсекеге қабілетті нәтиже.',
      risks: 'Базалық дайындығы әлсіз оқушыларға бейімделу қиынырақ.',
    },
  },
  'Cambridge Primary': {
    aliases: ['Cambridge Primary'],
    ru: {
      title: 'Cambridge Primary',
      short: 'Международная программа начальной школы Cambridge.',
      includes: 'Английский, математика и science, навыки мышления и коммуникации.',
      forWho: 'Для старта международной траектории с младших классов.',
      workload: 'Средняя',
      outcome: 'Сильная языковая и академическая база для следующих ступеней.',
      risks: 'Нужна поддержка английского, особенно в начале.',
    },
    en: {
      title: 'Cambridge Primary',
      short: 'International Cambridge pathway for primary grades.',
      includes: 'English, Math, Science and thinking/communication skill development.',
      forWho: 'Families starting an international pathway early.',
      workload: 'Medium',
      outcome: 'Strong language and academic foundation for next stages.',
      risks: 'Requires consistent English support at the beginning.',
    },
    kk: {
      title: 'Cambridge Primary',
      short: 'Cambridge бастауыш сыныптарына арналған халықаралық бағдарлама.',
      includes: 'Ағылшын, математика, science және ойлау/коммуникация дағдылары.',
      forWho: 'Ерте жастан халықаралық бағытты бастайтын отбасыларға.',
      workload: 'Орташа',
      outcome: 'Келесі кезеңдерге мықты тілдік және академиялық іргетас.',
      risks: 'Бастапқы кезеңде ағылшынға тұрақты қолдау қажет.',
    },
  },
  'Cambridge Lower Secondary': {
    aliases: ['Cambridge Lower Secondary'],
    ru: {
      title: 'Cambridge Lower Secondary',
      short: 'Средняя ступень Cambridge с подготовкой к IGCSE.',
      includes: 'Углубление ключевых предметов, аналитика, международные стандарты оценивания.',
      forWho: 'Тем, кто продолжает Cambridge-путь после начальной школы.',
      workload: 'Средняя-высокая',
      outcome: 'Плавный переход к IGCSE.',
      risks: 'Важно держать языковой и предметный темп.',
    },
    en: {
      title: 'Cambridge Lower Secondary',
      short: 'Cambridge middle-stage program leading toward IGCSE.',
      includes: 'Deeper core subjects, analytical tasks, international assessment style.',
      forWho: 'Students continuing the Cambridge track after primary.',
      workload: 'Medium-High',
      outcome: 'Smooth transition to IGCSE.',
      risks: 'Requires stable language and subject pace.',
    },
    kk: {
      title: 'Cambridge Lower Secondary',
      short: 'IGCSE-ге апаратын Cambridge орта буын бағдарламасы.',
      includes: 'Негізгі пәндерді тереңдету, аналитикалық тапсырмалар, халықаралық бағалау стилі.',
      forWho: 'Cambridge жолын бастауыштан кейін жалғастыратын оқушыларға.',
      workload: 'Орташа-жоғары',
      outcome: 'IGCSE-ге бірқалыпты көшу.',
      risks: 'Тілдік және пәндік қарқынды тұрақты ұстау маңызды.',
    },
  },
  'Cambridge IGCSE': {
    aliases: ['Cambridge IGCSE'],
    ru: {
      title: 'Cambridge IGCSE',
      short: 'Международная предметная программа старших классов.',
      includes: 'Выбор предметов, системная экзаменационная подготовка, академическое письмо и анализ.',
      forWho: 'Для подготовки к A-Level, IB и международному поступлению.',
      workload: 'Высокая',
      outcome: 'Признанные международные академические результаты.',
      risks: 'Высокая экзаменационная нагрузка и требования к дисциплине.',
    },
    en: {
      title: 'Cambridge IGCSE',
      short: 'International subject-based upper-grade program.',
      includes: 'Subject choice, structured exam prep, academic writing and analysis.',
      forWho: 'Students preparing for A-Level, IB, and global university pathways.',
      workload: 'High',
      outcome: 'Internationally recognized academic outcomes.',
      risks: 'High exam pressure and strong discipline required.',
    },
    kk: {
      title: 'Cambridge IGCSE',
      short: 'Жоғары сыныптарға арналған халықаралық пәндік бағдарлама.',
      includes: 'Пән таңдау, жүйелі емтиханға дайындық, академиялық жазу және талдау.',
      forWho: 'A-Level, IB және халықаралық ЖОО бағытына дайындалатындарға.',
      workload: 'Жоғары',
      outcome: 'Халықаралық деңгейде танылатын академиялық нәтиже.',
      risks: 'Емтихан жүктемесі жоғары, тәртіп қажет.',
    },
  },
  'Cambridge A-Level': {
    aliases: ['Cambridge A-Level'],
    ru: {
      title: 'Cambridge A-Level',
      short: 'Предуниверситетская программа с углублением 3-4 предметов.',
      includes: 'Глубокая профильная подготовка, сложные задачи, международные экзамены.',
      forWho: 'Для учеников с четким вузовским и карьерным профилем.',
      workload: 'Очень высокая',
      outcome: 'Сильная база для поступления в международные вузы.',
      risks: 'Требует зрелости, устойчивости к интенсивной академической нагрузке.',
    },
    en: {
      title: 'Cambridge A-Level',
      short: 'Pre-university track with deep specialization in 3-4 subjects.',
      includes: 'Advanced subject mastery, complex problem solving, international exams.',
      forWho: 'Students with clear university and career direction.',
      workload: 'Very High',
      outcome: 'Strong preparation for international universities.',
      risks: 'Requires maturity and stamina for intensive academics.',
    },
    kk: {
      title: 'Cambridge A-Level',
      short: '3-4 пәнді тереңдететін ЖОО-ға дейінгі бағдарлама.',
      includes: 'Терең профильдік дайындық, күрделі тапсырмалар, халықаралық емтихандар.',
      forWho: 'Университет бағытын нақты таңдаған оқушыларға.',
      workload: 'Өте жоғары',
      outcome: 'Халықаралық ЖОО-ға түсуге мықты база.',
      risks: 'Академиялық жүктемеге төзімділік пен жоғары жауапкершілік қажет.',
    },
  },
  'IB PYP': {
    aliases: ['IB PYP'],
    ru: {
      title: 'IB PYP',
      short: 'Начальная программа IB с обучением через исследование.',
      includes: 'Трансдисциплинарные темы, проекты, рефлексия и развитие learner profile.',
      forWho: 'Для семей, ценящих самостоятельность и критическое мышление.',
      workload: 'Средняя',
      outcome: 'Развитие исследовательских, коммуникативных и презентационных навыков.',
      risks: 'Может быть непривычно при ожидании классической системы.',
    },
    en: {
      title: 'IB PYP',
      short: 'IB primary program built around inquiry-based learning.',
      includes: 'Transdisciplinary themes, projects, reflection, learner profile growth.',
      forWho: 'Families prioritizing independence and critical thinking.',
      workload: 'Medium',
      outcome: 'Strong research, communication, and presentation skills.',
      risks: 'Can feel unfamiliar versus traditional instruction models.',
    },
    kk: {
      title: 'IB PYP',
      short: 'Зерттеуге негізделген IB бастауыш бағдарламасы.',
      includes: 'Трансдисциплинарлық тақырыптар, жобалар, рефлексия, learner profile.',
      forWho: 'Өзіндік жұмыс пен сыни ойлауды маңызды көретін отбасыларға.',
      workload: 'Орташа',
      outcome: 'Зерттеу, коммуникация және таныстырылым дағдылары дамиды.',
      risks: 'Дәстүрлі жүйеге үйренгендерге басында түсініксіз болуы мүмкін.',
    },
  },
  STEAM: {
    aliases: ['STEAM'],
    ru: {
      title: 'STEAM',
      short: 'Интеграция науки, технологий, инженерии, искусства и математики.',
      includes: 'Проектная работа, дизайн-мышление, практические и командные задачи.',
      forWho: 'Для детей, которым важно сочетание технологий и креативности.',
      workload: 'Средняя',
      outcome: 'Прикладные навыки, креативность и решение реальных задач.',
      risks: 'Качество сильно зависит от базы школы и наставников.',
    },
    en: {
      title: 'STEAM',
      short: 'Integrated Science, Technology, Engineering, Arts, and Math approach.',
      includes: 'Project work, design thinking, practical team-based challenges.',
      forWho: 'Students who need both technical and creative development.',
      workload: 'Medium',
      outcome: 'Applied skills, creativity, and real-world problem solving.',
      risks: 'Quality depends heavily on school facilities and mentors.',
    },
    kk: {
      title: 'STEAM',
      short: 'Ғылым, технология, инженерия, өнер және математиканы біріктіреді.',
      includes: 'Жобалық жұмыс, дизайн-ойлау, практикалық және командалық тапсырмалар.',
      forWho: 'Техника мен креативті қатар дамытқысы келетін балаларға.',
      workload: 'Орташа',
      outcome: 'Қолданбалы дағды, шығармашылық және нақты міндеттерді шешу.',
      risks: 'Сапасы мектептің базасы мен мұғалімдеріне қатты тәуелді.',
    },
  },
  STEM: {
    aliases: ['STEM'],
    ru: {
      title: 'STEM',
      short: 'Усиленный трек по науке, технологиям, инженерии и математике.',
      includes: 'Лабораторные и прикладные задачи, часто coding/robotics компоненты.',
      forWho: 'Для детей с интересом к техническим и инженерным направлениям.',
      workload: 'Средняя-высокая',
      outcome: 'Сильная подготовка к техническим олимпиадам и вузам.',
      risks: 'Может быть менее комфортно для гуманитарно ориентированных учеников.',
    },
    en: {
      title: 'STEM',
      short: 'Enhanced pathway in science, technology, engineering, and math.',
      includes: 'Lab and applied tasks, often with coding/robotics components.',
      forWho: 'Students interested in technical and engineering fields.',
      workload: 'Medium-High',
      outcome: 'Strong preparation for technical competitions and universities.',
      risks: 'May be less suitable for strongly humanities-focused students.',
    },
    kk: {
      title: 'STEM',
      short: 'Ғылым, технология, инженерия және математикаға күшейтілген бағыт.',
      includes: 'Зертханалық және қолданбалы тапсырмалар, жиі coding/robotics бар.',
      forWho: 'Техникалық және инженерлік бағытқа қызығатын оқушыларға.',
      workload: 'Орташа-жоғары',
      outcome: 'Техникалық олимпиада мен ЖОО-ға мықты дайындық.',
      risks: 'Гуманитарлық бағыты басым балаларға ыңғайсыз болуы мүмкін.',
    },
  },
  Montessori: {
    aliases: ['Montessori', 'Монтессори'],
    ru: {
      title: 'Монтессори',
      short: 'Методика самостоятельного обучения в подготовленной среде.',
      includes: 'Индивидуальный темп, практические материалы, развитие саморегуляции.',
      forWho: 'Для детей, которым важны мягкий ритм и самостоятельность.',
      workload: 'Средняя',
      outcome: 'Сильная внутренняя мотивация и навык самоорганизации.',
      risks: 'Требует совпадения с семейными ожиданиями к дисциплине и формату.',
    },
    en: {
      title: 'Montessori',
      short: 'Self-directed learning in a carefully prepared environment.',
      includes: 'Individual pace, hands-on materials, self-regulation development.',
      forWho: 'Students who thrive with autonomy and guided independence.',
      workload: 'Medium',
      outcome: 'Strong intrinsic motivation and self-organization skills.',
      risks: 'Must align with family expectations on structure and discipline.',
    },
    kk: {
      title: 'Монтессори',
      short: 'Дайындалған ортада өзіндік оқуға негізделген әдіс.',
      includes: 'Жеке қарқын, практикалық материалдар, өзін-өзі реттеу дағдылары.',
      forWho: 'Жұмсақ ырғақ пен дербестікті қажет ететін балаларға.',
      workload: 'Орташа',
      outcome: 'Ішкі мотивация және өзін-өзі ұйымдастыру қабілеті дамиды.',
      risks: 'Отбасының тәртіп пен форматқа көзқарасымен сәйкес болуы керек.',
    },
  },
  Waldorf: {
    aliases: ['Waldorf', 'Вальдорфская', 'Вальдорф'],
    ru: {
      title: 'Вальдорф',
      short: 'Гуманистическая педагогика с акцентом на творчество и развитие по возрасту.',
      includes: 'Искусство, ремесла, движение, интеграция академических и творческих блоков.',
      forWho: 'Для семей, которым важна целостная и мягкая образовательная среда.',
      workload: 'Средняя',
      outcome: 'Развитие воображения, эмоционального интеллекта и устойчивой мотивации.',
      risks: 'Нужно заранее уточнять формат аттестации и переходов в другие школы.',
    },
    en: {
      title: 'Waldorf',
      short: 'Human-centered pedagogy focused on creativity and age-based development.',
      includes: 'Arts, crafts, movement, and integrated academic-creative blocks.',
      forWho: 'Families seeking a holistic and softer learning environment.',
      workload: 'Medium',
      outcome: 'Strong imagination, emotional intelligence, and durable motivation.',
      risks: 'Clarify assessment and transfer pathways in advance.',
    },
    kk: {
      title: 'Вальдорф',
      short: 'Шығармашылық пен жас ерекшелігіне сай дамуға бағытталған педагогика.',
      includes: 'Өнер, қолөнер, қимыл және академиялық/шығармашылық блоктардың интеграциясы.',
      forWho: 'Тұтас әрі жұмсақ білім беру ортасын қалайтын отбасыларға.',
      workload: 'Орташа',
      outcome: 'Қиял, эмоциялық интеллект және тұрақты мотивация дамиды.',
      risks: 'Бағалау және басқа мектепке ауысу тәртібін алдын ала нақтылау керек.',
    },
  },
  'American Curriculum': {
    aliases: ['American Curriculum', 'Американская программа', 'Америкалық бағдарлама'],
    ru: {
      title: 'Американская программа',
      short: 'Обучение по американским стандартам с гибким выбором предметов.',
      includes: 'Grade-based система, elective-предметы, coursework и continuous assessment.',
      forWho: 'Для тех, кто целится в международные вузы и гибкую траекторию.',
      workload: 'Средняя-высокая',
      outcome: 'Широкий академический профиль и подготовка к международному поступлению.',
      risks: 'Сильная зависимость качества от конкретной школы и аккредитации.',
    },
    en: {
      title: 'American Curriculum',
      short: 'US-style standards with flexible subject selection.',
      includes: 'Grade-based system, electives, coursework, and continuous assessment.',
      forWho: 'Families aiming for flexible pathways and global university options.',
      workload: 'Medium-High',
      outcome: 'Broad academic profile and international admissions readiness.',
      risks: 'Quality varies significantly by school implementation and accreditation.',
    },
    kk: {
      title: 'Америкалық бағдарлама',
      short: 'Пән таңдауы икемді, америкалық стандартқа негізделген оқу.',
      includes: 'Grade-based жүйе, elective пәндер, coursework және тұрақты бағалау.',
      forWho: 'Халықаралық ЖОО-ға бағыт пен икемді траектория қажет отбасыларға.',
      workload: 'Орташа-жоғары',
      outcome: 'Кең академиялық профиль және халықаралық түсуге дайындық.',
      risks: 'Сапасы мектептің іске асыруы мен аккредитациясына қатты тәуелді.',
    },
  },
  'British National Curriculum': {
    aliases: ['British National Curriculum', 'Британская программа', 'Британская национальная программа', 'Британ ұлттық бағдарламасы'],
    ru: {
      title: 'Британская национальная программа',
      short: 'Структурированная система по Key Stages и предметным стандартам.',
      includes: 'Четкие академические цели по возрасту, системная подготовка к GCSE/A-Level.',
      forWho: 'Для семей, которым важна строгая последовательность и академическая дисциплина.',
      workload: 'Высокая',
      outcome: 'Прочный международно признанный академический трек.',
      risks: 'Высокая требовательность к темпу и академической организованности.',
    },
    en: {
      title: 'British National Curriculum',
      short: 'Structured Key Stage pathway with clear subject standards.',
      includes: 'Age-specific academic goals and preparation for GCSE/A-Level tracks.',
      forWho: 'Families valuing structure, sequence, and academic discipline.',
      workload: 'High',
      outcome: 'Strong internationally recognized academic pathway.',
      risks: 'Demands steady pace and high academic organization.',
    },
    kk: {
      title: 'Британ ұлттық бағдарламасы',
      short: 'Key Stages пен айқын пәндік стандарттарға құрылған құрылымды жүйе.',
      includes: 'Жасқа сай академиялық мақсаттар, GCSE/A-Level-ге жүйелі дайындық.',
      forWho: 'Құрылым мен академиялық тәртіпті маңызды көретін отбасыларға.',
      workload: 'Жоғары',
      outcome: 'Халықаралық деңгейде танылатын мықты академиялық траектория.',
      risks: 'Қарқын мен ұйымдасуға жоғары талап қояды.',
    },
  },
  'Bilingual Program': {
    aliases: ['Bilingual Program', 'Билингвальная программа', 'Қостілді бағдарлама'],
    ru: {
      title: 'Билингвальная программа',
      short: 'Обучение на двух языках по одной академической траектории.',
      includes: 'Предметы на двух языках, языковая иммерсия, развитие академической лексики.',
      forWho: 'Для семей, где важны сильные языковые навыки и международная мобильность.',
      workload: 'Средняя-высокая',
      outcome: 'Рост двуязычия и уверенное предметное общение на двух языках.',
      risks: 'Важно контролировать, чтобы предметные результаты не проседали из-за языковой нагрузки.',
    },
    en: {
      title: 'Bilingual Program',
      short: 'Two-language instruction within one academic pathway.',
      includes: 'Subjects taught in two languages, immersion, academic vocabulary growth.',
      forWho: 'Families prioritizing strong language outcomes and mobility.',
      workload: 'Medium-High',
      outcome: 'Strong bilingual proficiency with subject-level communication.',
      risks: 'Monitor core subject progress while language load increases.',
    },
    kk: {
      title: 'Қостілді бағдарлама',
      short: 'Бір академиялық траекторияда екі тілде оқыту.',
      includes: 'Пәндерді екі тілде оқу, иммерсия, академиялық лексиканы дамыту.',
      forWho: 'Тілдік нәтиже мен халықаралық икемділік маңызды отбасыларға.',
      workload: 'Орташа-жоғары',
      outcome: 'Екі тілде сенімді пәндік коммуникация қалыптасады.',
      risks: 'Тілдік жүктеме артқанда негізгі пән нәтижесін бақылау қажет.',
    },
  },
  'Author program': {
    aliases: ['Author program', 'Авторская программа', 'Авторлық бағдарлама'],
    ru: {
      title: 'Авторская программа',
      short: 'Собственная образовательная модель конкретной школы.',
      includes: 'Уникальные курсы, методики, оценивание и формат учебного процесса.',
      forWho: 'Для семей, которым важен особый профиль школы и нестандартный подход.',
      workload: 'Зависит от школы',
      outcome: 'Может дать сильный профиль в выбранных направлениях.',
      risks: 'Нужно отдельно проверять аккредитацию, аттестацию и сопоставимость с внешними стандартами.',
    },
    en: {
      title: 'Author program',
      short: 'A school-specific custom educational model.',
      includes: 'Unique courses, methods, assessment rules, and learning format.',
      forWho: 'Families seeking a distinctive school profile and non-standard approach.',
      workload: 'Depends on school',
      outcome: 'Can provide strong specialization in selected domains.',
      risks: 'Verify accreditation, assessment model, and comparability with external standards.',
    },
    kk: {
      title: 'Авторлық бағдарлама',
      short: 'Нақты мектеп әзірлеген жеке білім беру моделі.',
      includes: 'Бірегей курстар, әдістемелер, бағалау және оқу форматы.',
      forWho: 'Мектептің ерекше профилі мен стандарттан тыс тәсілді іздейтін отбасыларға.',
      workload: 'Мектепке байланысты',
      outcome: 'Таңдалған бағыттарда күшті мамандану бере алады.',
      risks: 'Аккредитация, аттестация және сыртқы стандарттармен сәйкестігін міндетті түрде тексеру қажет.',
    },
  },
};

const normalizeProgramValue = (value) =>
  String(value || '')
    .trim()
    .toLowerCase()
    .replace(/\s+/g, ' ');

const INDEX_BY_ALIAS = Object.entries(CURRICULA_INFO).reduce((acc, [key, value]) => {
  [key, ...(value.aliases || [])].forEach((alias) => {
    const normalized = normalizeProgramValue(alias);
    if (normalized) acc[normalized] = key;
  });
  return acc;
}, {});

export const resolveCurriculaKey = (value) =>
  INDEX_BY_ALIAS[normalizeProgramValue(value)] || null;

export const getCurriculaInfo = (value, locale = 'ru') => {
  const canonicalKey = resolveCurriculaKey(value);
  if (!canonicalKey) return null;
  const node = CURRICULA_INFO[canonicalKey];
  const safeLocale = locale === 'kk' || locale === 'en' ? locale : 'ru';
  return node[safeLocale] || node.ru;
};

export { CURRICULA_INFO };
